#import <Foundation/Foundation.h>
#import "SWGGetSystemCurrencyRequest.h"
#import "SWGServerResponse.h"
#import "SWGApi.h"

/**
* 同城家教 API
* 同城家教 接口文档, V1.0
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGBaseApi: NSObject <SWGApi>

extern NSString* kSWGBaseApiErrorDomain;
extern NSInteger kSWGBaseApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 获取系统的金币名称
/// APP获取系统货币名称
///
/// @param getSystemCurrency APP获取系统货币名称
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) getSystemCurrencyWithGetSystemCurrency: (SWGGetSystemCurrencyRequest*) getSystemCurrency
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;



@end
