#import <Foundation/Foundation.h>
#import "SWGChangePasswordRequest.h"
#import "SWGCheckVarcodeRequest.h"
#import "SWGGetPhoneVarcodeRequest.h"
#import "SWGLoginRequest.h"
#import "SWGRegisterRequest.h"
#import "SWGRetrievePasswordRequest.h"
#import "SWGServerResponse.h"
#import "SWGApi.h"

/**
* 同城家教 API
* 同城家教 接口文档, V1.0
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/



@interface SWGUserApi: NSObject <SWGApi>

extern NSString* kSWGUserApiErrorDomain;
extern NSInteger kSWGUserApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(SWGApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// 用户注册操作
/// 注册
///
/// @param _register 注册
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) callRegisterWithRegister: (SWGRegisterRequest*) _register
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;


/// 修改密码
/// 修改密码
///
/// @param changePassword 修改密码
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) changePasswordWithChangePassword: (SWGChangePasswordRequest*) changePassword
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;


/// 验证码校验
/// 判断用户输入的验证码是否正确
///
/// @param checkVarcode 判断用户输入的验证码是否正确
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) checkVarcodeWithCheckVarcode: (SWGCheckVarcodeRequest*) checkVarcode
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;


/// 获取验证码
/// 获取验证码
///
/// @param getPhoneVarcode 获取验证码
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) getPhoneVarcodeWithGetPhoneVarcode: (SWGGetPhoneVarcodeRequest*) getPhoneVarcode
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;


/// 用户登录操作
/// 登录
///
/// @param login 登录
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) loginWithLogin: (SWGLoginRequest*) login
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;


/// 重置密码
/// 忘记密码，进行重置
///
/// @param retrievePassword 重置密码
/// 
///  code:200 message:"server response success",
///  code:0 message:"操作成功"
///
/// @return SWGServerResponse*
-(NSURLSessionTask*) retrievePasswordWithRetrievePassword: (SWGRetrievePasswordRequest*) retrievePassword
    completionHandler: (void (^)(SWGServerResponse* output, NSError* error)) handler;



@end
