#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 同城家教 API
* 同城家教 接口文档, V1.0
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGGetPhoneVarcodeRequest
@end

@interface SWGGetPhoneVarcodeRequest : SWGObject

/* mobile phone 
 */
@property(nonatomic) NSString* mobileNum;
/* 1:register,2:forget password,3:bind phone 
 */
@property(nonatomic) NSNumber* type;

@end
