#import <Foundation/Foundation.h>
#import "SWGObject.h"

/**
* 同城家教 API
* 同城家教 接口文档, V1.0
*
* OpenAPI spec version: 1.0
* 
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/





@protocol SWGRegisterRequest
@end

@interface SWGRegisterRequest : SWGObject

/*  
 */
@property(nonatomic) NSString* mobileNum;
/*  
 */
@property(nonatomic) NSString* password;
/*  
 */
@property(nonatomic) NSString* varcode;
/*  [optional]
 */
@property(nonatomic) NSString* userNicename;
/* 0:student,1:teacher [optional]
 */
@property(nonatomic) NSNumber* isTutor;
/*  [optional]
 */
@property(nonatomic) NSString* promoteCode;

@end
